# Default values for cicd-practise-3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/superads-sdk/cicd-practise-3
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab

nameOverride: ""
fullnameOverride: ""
