apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-mymain1
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: cronjob-mymain1
            app.kubernetes.io/instance: {{ .Release.Name }}
          annotations:
            timestamp: "{{ date "20060102150405" .Release.Time }}"
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          containers:
            - name: cronjob-mymain1
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - "com.example.demo.MyMain1"
          restartPolicy: OnFailure