apiVersion: v1
kind: Service
metadata:
  name: my-internal-service
spec:
  selector:
    app: service_test_pod
  type: ClusterIP
  ports:
  - name: http99
    port: 99
    targetPort: 9999
    protocol: TCP
